### ISSUE TITLE
长音频如何处理？长音频调用只输出一半对应的文本

### ISSUE THREAD

**Issue by xxm1668** [QwenLM/Qwen-Audio#10]

**Comment by flowbywind** [comment]
同样的问题 目前看默认是30s

**Comment by faychu** [comment]
您好，目前Qwen-Audio只支持30s以内的音频分析，超过30s的音频会进行截断（相关代码见 https://github.com/QwenLM/Qwen-Audio/blob/main/audio.py#L98）。

**Comment by flowbywind** [comment]
> https://github.com/QwenLM/Qwen-Audio/blob/main/audio.py#L98）。

那如果想超过30s 怎么处理

**Comment by AMAG-AB** [comment]
同问
