### ISSUE TITLE
开源时间提问

### ISSUE THREAD

**Issue by Mddct** [QwenLM/Qwen-Audio#2]
Geat work！Is there a timetable for open source to reproduce and checkpoint ?

**Comment by changzhou-pku** [comment]
We plan to release the model checkpoint, online API and interactive demo at the end of Nov.

**Comment by Mddct** [comment]
thx， and Are the training code and data open source?

**Comment by lingfengchencn** [comment]
期待ing

**Comment by Bald0Wang** [comment]
期待27日打卡

**Comment by pigorz** [comment]
期待ing

**Comment by White-Friday** [comment]
期待，29号，倒数第二天打卡

**Comment by Bald0Wang** [comment]
哈哈  跟上 29日打卡

**Comment by KMnO4-zx** [comment]
期待 11月29日上午9点23打卡

**Comment by Zth9730** [comment]
跟紧 11月29日上午11点28分打卡

**Comment by Bald0Wang** [comment]
期待11月30日打卡

**Comment by lingfengchencn** [comment]
期待11月30日打卡，

**Comment by ChuxiJ** [comment]
11月30日打卡~

**Comment by zxy-zzz** [comment]
> 11月30日打卡~

https://modelscope.cn/models/qwen/Qwen-Audio-Chat/summary
