### ISSUE TITLE
It's just an advertise. No code No model

### ISSUE THREAD

**Issue by yangboyd** [QwenLM/Qwen-Audio#3]
It's just an advertise. No code No model

**Comment by Jxu-Thu** [comment]
We are working hardly to complete code cleaning and transition the model to Hugging Face for wider usage. Our models will be released in a few weeks.

**Comment by yiiizhang** [comment]
> We are working hardly to complete code cleaning and transition the model to Hugging Face for wider usage. Our models will be released in a few weeks.

Are the training code be open source?
