### ISSUE TITLE
请问prompt要怎么写才能获得单个task的信息或者想要的task的信息？

### ISSUE THREAD

**Issue by wjyfelicity** [QwenLM/Qwen-Audio#32]
我这边想进行情感识别时，将prompt='<audio>{audio_url}</audio><|emotion_recognition|>'时，出来的结果是：
<audio>assets/audio/1.wav</audio><|emotion_recognition|><|zh|><|transcribe|><|zh|><|notimestamps|><|speaker_meta|>普通话, 女声, 31岁<|startoftranscript|><|zh|><|transcribe|><|zh|><|notimestamps|><|wo_itn|>今天天气真好<|endoftext|>
可以看到上面的结果，包含普通话，性别，年龄和文本，但是就是没有情感，那么写prompt的时候，要怎么写才能获得单个task的信息或者想要的task的信息。

**Comment by yangjiabupt** [comment]
<audio>{}</audio><|startofanalysis|><|en|><|keyword|><|en|><|notimestamps|><|emotion_recognition|>这样才行

**Comment by yangjiabupt** [comment]
但是感觉模型的泛化性一般，在新的数据上表现很差的
