### ISSUE TITLE
qwen-audio 微调

### ISSUE THREAD

**Issue by wjfwjfwjf** [QwenLM/Qwen-Audio#38]
我参照qwen-vl写了一个微调代码，能跑起来，但可能有些问题，仅供参考
[finetune.zip](https://github.com/QwenLM/Qwen-Audio/files/14156253/finetune.zip)

**Comment by wangwang110** [comment]
有跑起来的数据样例吗？

**Comment by wjfwjfwjf** [comment]
[
[test.json](https://github.com/QwenLM/Qwen-Audio/files/14468306/test.json)
](url)
脚本是参照qwen_vl写的，上面是样例数据，和qwen_vl类似
