### ISSUE TITLE
is that possible to do tts and speaker diarizatoin?

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen-Audio#4]
is that possible to do tts and speaker diarizatoin?

**Comment by Maggione** [comment]
Qwen-Audio is an audio understanding model that currently does not support audio generation. 
It can be used as an input processing model for audio generation tasks, such as the mentioned speech editing function in our paper. By utilizing Qwen-Audio to comprehend the original speech, speech editing can be achieved through external tools.
