### ISSUE TITLE
怎样可以让asr的输出带标点呢

### ISSUE THREAD

**Issue by liuxq** [QwenLM/Qwen-Audio#6]

**Comment by faychu** [comment]
可以尝试Qwen-Audio的inference时，用以下prompt：
中文ASR：'<|startoftranscript|><|zh|><|transcribe|><|zh|><|notimestamps|><|itn|>'
英文ASR：'<|startoftranscript|><|en|><|transcribe|><|en|><|notimestamps|><|itn|>'
